### ISSUE TITLE
CRAN issue - Non-API entry points into R

### ISSUE THREAD

**Issue by beniaminogreen** [beniaminogreen/zoomerjoin#121]
[The CRAN builder is currently showing the following issues when building zoomerjoin](https://cran.r-project.org/web/checks/check_results_zoomerjoin.html): 

> Version: 0.1.4
Check: compiled code
Result: NOTE
  File ‘zoomerjoin/libs/zoomerjoin.so’:
    Found non-API calls to R: ‘ENVFLAGS’, ‘FRAME’, ‘HASHTAB’, ‘PRCODE’,
      ‘PRENV’, ‘PRSEEN’, ‘PRVALUE’, ‘Rf_findVarInFrame3’, ‘SET_BODY’,
      ‘SET_CLOENV’, ‘SET_ENCLOS’, ‘SET_ENVFLAGS’, ‘SET_FORMALS’,
      ‘SET_PRCODE’, ‘SET_PRENV’, ‘SET_PRVALUE’, ‘STRING_PTR’, ‘SYMVALUE’,
      ‘XLENGTH_EX’
Compiled code should not call non-API entry points in R.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.

Unsure why this is the case + why CRAN is suddenly giving NOTEs when it was not before (could this be an rextendr issue?). Opening this issue to track my work as I investigate what's going on + to solicit help if anyone is familiar with this issue.

**Comment by etiennebacher** [comment]
In case you haven't found out already, this is an issue coming from R-devel where they are rearranging a lot of the C entry points and marking a bunch of them as non-API, meaning that they shouldn't be used. Those NOTEs appear because `extendr` uses some of those non-API calls (see e.g. https://github.com/extendr/extendr/issues/806).

You're clearly not alone on this, see the `extendr` repo (`rlang` also has some issues with that). I don't think it would be useful to contact them for now (they are aware of this issue) but I'd suggest you keep an eye on it.

**Comment by CGMossa** [comment]
With #122, I guess this issue is resolved? Fell free to ping us again, but we are most likely aware of when these things happen, because we have r-cmd-check in our CI.
