### ISSUE TITLE
Reviewing

### ISSUE THREAD

**Issue by wincowgerDEV** [beniaminogreen/zoomerjoin#76]
Additional review comments for https://github.com/openjournals/joss-reviews/issues/5693

Usages in the readme should have consistent a naming convention for the functions: https://github.com/beniaminogreen/zoomerjoin#usage

The jaccard_full_join() has parentheses but euclidean_full_join doesn't which makes it appear like the euclidean functions are actually objects.

**Comment by wincowgerDEV** [comment]
Check that the function examples in help would run if a user has little experience with R. 

For example ```jaccard_anti_join()``` requires the user to have ```library(babynames)``` but it really should start with installing that package if the user doesn't have it.

**Comment by wincowgerDEV** [comment]
https://github.com/beniaminogreen/zoomerjoin#example-joining-rows-of-the-database-on-ideology-money-in-politics-and-elections

It looks like you actually have this dataset loading into zoomerjoin?

Why not read in this instead of calling an object that the user doesn't immediately have access to? Given this link (https://data.stanford.edu/dime) it isn't immediately obvious which is corpus 1 and which is corpus 2. 

```zoomerjoin::dime_data```

**Comment by wincowgerDEV** [comment]
The vignette needs to read in dplyr here: http://beniamino.org/zoomerjoin/articles/guided_tour.html#basic-syntax

**Comment by wincowgerDEV** [comment]
In the vignette I was surprised that ```print(join_out)``` produced a different number of rows than in the example, mine has 47886 while yours has 48106. Is this because of the probabilistic framework?

**Comment by wincowgerDEV** [comment]
Typo in ```jaacrd_curve``` in the vignette.

**Comment by wincowgerDEV** [comment]
There seems to be quite a bit of variability in the run time between devices for different functions. 

The euclidean_inner_join example is taking much longer on my device than 30 seconds (several minutes already) http://beniamino.org/zoomerjoin/articles/matching_vectors.html

Also join_out example in the vignette took only 3 seconds on my machine.

**Comment by beniaminogreen** [comment]
Thanks for such detailed feedback on the package. I'll shortly create a branch for processing all these. 

It seems that a common thread between all of these  is that the code examples in the function documentations need to be streamlined and checked so they run quickly and without errors.  I'll work on this in the next few days, as well as fixing typos / responding to the other comments. 

Based on a comment from the other reviewer, I decided to package a copy of the DIME donor dataset with Zoomerjoin to make the examples more accessible to users. The two corpuses are just random subsets of the donors listed in the database (contrived, but consistent with a previous paper on fuzzy-joining in the field) I'll make this more clear in the documentation as well. 

The varying number of observations in the joined dataset is indeed due to the probabilistic algorithm.  For my use cases, I just set the `n_bands` parameter, which governs how many matches can be discarded due to chance, high enough that the results are consistent every run.   This probably isn't ideal from a reproducibility perspective, so I'll create a PR to make the Rust code take the random seed from R so results can be replicated with `set.seed`. 

Best, and thanks, 
Ben

**Comment by beniaminogreen** [comment]
To do for this thread: 
 
- [ ] add babynames install / import to examples or change to use the dataset packaged with zoomerjoin. 
 - [ ] make sure all functions are labelled with `function()` not `function` in the documentation
 - [ ] Take the random seed from R and pass to Rust
 - [ ] Set seed in all vingettes so results are reproducible
 - [ ] fix `jaccard_crve` typo
